### ISSUE TITLE
__getitem__ / get_from raises KeyError when key is numeric string.

### ISSUE THREAD

**Issue by gilabrantes** [pawelzny/dotty_dict#50]
KeyError is thrown instead of existing value.
Everything works when the numeic key is a numeric type (i.e. int)

Reproducing steps:
```
Python 3.6.8 (default, Aug 20 2019, 17:12:48)                                                                          
[GCC 8.3.0] on linux                                                                                                   
Type "help", "copyright", "credits" or "license" for more information.                                                 
>>> from dotty_dict import dotty                                                                                       
>>> dict_data = {'a': {'1': 'a_one'}}                                                                                  
>>> a = dotty(dict_data)                                                                                               
>>> a['a.1']                                                                                                           
Traceback (most recent call last):                                                                                     
  File "<stdin>", line 1, in <module>                                                                                  
  File "/home/gil/.virtualenvs/Sandbox/lib/python3.6/site-packages/dotty_dict/dotty_dict.py", line 139, in __getitem__ 
    return get_from(self._split(item), self._data)                                                                     
  File "/home/gil/.virtualenvs/Sandbox/lib/python3.6/site-packages/dotty_dict/dotty_dict.py", line 135, in get_from    
    return get_from(items, data)                                                                                       
  File "/home/gil/.virtualenvs/Sandbox/lib/python3.6/site-packages/dotty_dict/dotty_dict.py", line 131, in get_from    
    data = data[it]                                                                                                    
KeyError: 1                                                                                                            
>>>
```

Also:
```
>>> dict_data = {'2': 'b'}
>>> a = dotty(dict_data)
>>> a[2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gil/.virtualenvs/Sandbox/lib/python3.6/site-packages/dotty_dict/dotty_dict.py", line 139, in __getitem__
    return get_from(self._split(item), self._data)
  File "/home/gil/.virtualenvs/Sandbox/lib/python3.6/site-packages/dotty_dict/dotty_dict.py", line 307, in _split
    key = key.replace(*skp_stamp).replace(*esc_stamp)
AttributeError: 'int' object has no attribute 'replace'
>>> a['2']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gil/.virtualenvs/Sandbox/lib/python3.6/site-packages/dotty_dict/dotty_dict.py", line 139, in __getitem__
    return get_from(self._split(item), self._data)
  File "/home/gil/.virtualenvs/Sandbox/lib/python3.6/site-packages/dotty_dict/dotty_dict.py", line 131, in get_from
    data = data[it]
KeyError: 2
>>>
```

Ubuntu @ Windows Subsystem Linux | Windows 10

**Comment by pawelzny** [comment]
It is definitely a bug. We will fix it shortly. Please be patient. Thank you for submission.

**Comment by pawelzny** [comment]
Hi @gilabrantes 

Fix has been merged to master. Please install dotty_dict from last commit and tell us if this solves your problem. If so, I will make a new release.

```
pip install git+git://github.com/pawelzny/dotty_dict.git@5c14a706d8c928fb389dd0d2e52baeccd0780de6
```

**Comment by gilabrantes** [comment]
Hi @pawelzny 

Apologies for the delay.
My previous failing conditions now work well and the bug seems to be fixed.

Although:
```
Python 3.6.8 (default, Aug 20 2019, 17:12:48)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dotty_dict import dotty
>>> dict_data = {'2': 'c'}
>>> a = dotty(dict_data)
>>> a['2']
'c'
>>> a[2]
'c'
```
Shouldn't a[2] raise KeyError?

Also here: 
```
>>> another_dict_data = {2: 'c'}
>>> b = dotty(another_dict_data)
>>> b[2]
'c'
>>> b['2']
'c'
```
Shouldn't b['2'] raise a KeyError?

**Comment by Dysproz** [comment]
That’s expected.
Because generally keys are passed as string ‘key1.key2.key3’ we don’t know whether e.g. key2 will be string, integer or other type.

Because of that dotty checks all types present in this sub-dict and tries to fit string key into other type key.

In your case you have top level key which is integer. Calling this key with string is the same as you’d call it as nested key with few keys joined with dots (but here are no dots, because there’s only one key).

 However, as additional feature we support usage of native key type to top level keys (so your key can be called with index 2 as integer, but you can’t call nested keys as integer e.g. dot[‘field’.2]).

In my last commit I added Limitations section to README which specifies some limits.

**Comment by gilabrantes** [comment]
Understood, I now see this was by design.

IMO for single keys it should behave like a standard dictionary: str(2) should not be the same as int('2'); One way to achieve this could be by checking whether the key string contains any separator charaters and if not, take it as it's native type.

Having said that, I can live with this limitation.
