### ISSUE TITLE
Setup py error

### ISSUE THREAD

**Issue by Laksh1997** [pawelzny/dotty_dict#63]
Hello, getting this error when installing the package in CICD

```
Collecting dotty-dict
  Downloading dotty_dict-1.2.1.tar.gz (37 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/user/miniconda/envs/py36/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-rm8rt_sd/dotty-dict/setup.py'"'"'; __file__='"'"'/tmp/pip-install-rm8rt_sd/dotty-dict/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-bo5mkxxv
         cwd: /tmp/pip-install-rm8rt_sd/dotty-dict/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rm8rt_sd/dotty-dict/setup.py", line 16, in <module>
        readme = readme_file.read()
      File "/home/user/miniconda/envs/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 113: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Dysproz** [comment]
Hi @Laksh1997,
Can you provide more information about environment that you use?
As I understand it's probably some container used in CI/CD.

In one of projects that I used to work in I had similar problem and solution was to set additional environment variables `LC_ALL="en_US.utf-8", LANG="en_US.utf-8"`.
You may try this, but I need more information about your test environment to check that.

**Comment by Laksh1997** [comment]
I tried the above but that didn't work

**Comment by Dysproz** [comment]
Sorry, but it seems like it's problem with your setup in CI/CD environment. Without details I'm not able to help you.
